import Head from "next/head";
import Header from "../components/Header";

export default function About() {
  return (
    <div className=''>
      <Head>
        <title>About</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
    </div>
  );
}
