import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Newsletter from "../components/Newsletter";
import Products from "../components/Products";
import Showcase from "../components/Showcase";
import Subscribe from "../components/Subscribe";
import Testimonials from "../components/Testimonials";

export default function Home() {
  return (
    <div className='relative'>
      <Head>
        <title>Infinity Designs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
    <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZZRSF3BWDH"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

       gtag('config', 'G-ZZRSF3BWDH');
      </script>
      </Head>

      <Header />
      <Hero />
      <Showcase />
      <Products />
      {/* <Testimonials /> */}
      <Newsletter />
      <Footer />
    </div>
  );
}
