import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Newsletter from "../components/Newsletter";
import Products from "../components/Products";
import Showcase from "../components/Showcase";
import Subscribe from "../components/Subscribe";
import Testimonials from "../components/Testimonials";

export default function Home() {
  return (
    <div className='relative'>
      <Head>
        <title>Infinity Designs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        </Head>

      <Header />
      <Hero />
      <Showcase />
      <Products />
      {/* <Testimonials /> */}
      <Newsletter />
      <Footer />
    </div>
  );
}
