import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";

export default function Vendor() {
  return (
    <div className=''>
      <Head>
        <title>Vendor Contact</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className='vc-banner h-[400px] w-full relative'>
        <h1 className='absolute left-0 right-0 px-8 bottom-36 flex justify-center items-center text-white text-4xl md:text-6xl lg:text-8xl'>
          Vendor Contact
        </h1>
      </div>
      <div className='flex justify-center px-2 lg:px-12 gap-8 mt-[60px] mb-[120px] lg:flex-row flex-col overflow-hidden'>
        <div className='flex flex-col flex-1 items-center'>
          <video width='640' height='360' controls>
            <source src='/videos/vendor.mp4' type='video/mp4'></source>
          </video>
          {/* <iframe
            src='https://player.vimeo.com/video/773219845?h=73e19fed03'
            width='640'
            height='360'
            frameborder='0'
            allow='autoplay; fullscreen'
            className='lg:mb-12 w-full'></iframe> */}
          <div className='text-center mt-[50px]'>
            <h1 className='text-4xl font-bold tracking-wider mb-5'>
              We believe suppliers to engage in transparent & ethical business
              practices.
            </h1>
            <button className='mt-8 bg-[#e8c085] flex justify-center mx-auto gap-1 items-center text-white p-2 hover:bg-[#e8b871] text-lg rounded-lg'>
              <a href='https://share-eu1.hsforms.com/1M0vmMuJhT-OqEw-iU9JdCwfui2i'>
                Download Form
              </a>
            </button>
          </div>
        </div>
        <div className='flex-1'>
          <iframe
            src='https://share-eu1.hsforms.com/1M0vmMuJhT-OqEw-iU9JdCwfui2i'
            width='640'
            height='1500'>
            Loading…
          </iframe>
        </div>
      </div>
      <Footer />
    </div>
  );
}
